# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
